In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [27]:
df1 = pd.read_csv('close\SamsungS7 Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('close\SamsungS7 Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)

df = df.set_index('TimeStamp')

df.to_csv('close\SamsungS7.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
1269744762646800,9,100,19990000,-19,100,1,12.830.445,4.806
1269744796061000,11,100,19990000,-19,100,1,12.830.445,4.806
1269744829403380,9,100,19990000,-19,100,1,12.830.445,4.806
1269744862620840,10,100,19990000,-19,100,1,12.830.445,4.806
1269744896026730,10,100,19990000,-19,100,1,12.830.445,4.806

In [28]:
df1 = pd.read_csv('close\Honor7x Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('close\Honor7x Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)
df = df.set_index('TimeStamp')

df.to_csv('close\Honor7x.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
135044726315330,2,100,24999000,-4,437,1,17.036.726,3.0
135044759566893,2,100,24999000,-4,437,1,17.036.726,3.0
135044792683038,2,100,24999000,-4,437,1,17.036.726,3.0
135044826016893,2,100,24999000,-4,437,1,17.036.726,3.0
135044859807518,2,100,24999000,-4,437,1,17.036.726,3.0

In [31]:
df1 = pd.read_csv('close\One Plus 2 Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('close\One Plus 2 Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)
df = df.set_index('TimeStamp')

df.to_csv('close\One Plus 2.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
74589360035273,17,100,10002455,-12,138,1,0.4651163,3.133
74589376699273,17,100,10002455,-12,138,1,0.4651163,3.133
74589393384273,17,100,10002455,-12,138,1,0.4651163,3.133
74589410039273,18,100,10002455,-12,138,1,0.4651163,3.133
74589426682273,17,100,10002455,-12,138,1,0.4651163,3.133

In [29]:
df1 = pd.read_csv('far\SamsungS7 Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('far\SamsungS7 Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)
df = df.set_index('TimeStamp')

df.to_csv('far\SamsungS7.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
1278362005884210,7,100,19990000,-20,100,1,0.587298,7.758
1278362205902940,6,100,19990000,-20,100,1,0.587298,7.758
1278362305875940,7,100,19990000,-20,100,1,0.587298,7.758
1278362339122710,7,100,19990000,-20,100,1,0.587298,7.758
1278362372443210,7,100,19990000,-20,100,1,0.587298,7.758

In [30]:
df1 = pd.read_csv('far\Honor7x Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('far\Honor7x Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)
df = df.set_index('TimeStamp')

df.to_csv('far\Honor7x.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
138001422935191,8,100,8333000,-4,80,1,0.0,2.959
138001456834150,3,100,8333000,-4,80,1,0.0,2.959
138001490287275,1,100,8333000,-4,80,1,0.0,2.959
138001522892483,9,100,8333000,-4,80,1,0.0,2.959
138001556670087,13,100,8333000,-4,80,1,0.0,2.959

In [32]:
df1 = pd.read_csv('far\One Plus 2 Hue Values.csv', delimiter = ';')
df2 = pd.read_csv('far\One Plus 2 Parameters.csv', delimiter = ';')

df = pd.merge(df1,df2)
df = df.set_index('TimeStamp')

df.to_csv('far\One Plus 2.csv', sep = ';')
df.head()

,Hue,Brightness,ExposureTime,ExposureComp,ISO,AWB,FocusDist,Zoom
TimeStamp,,,,,,,,
75701051090273,8,100,10002455,-12,242,1,10.344.828,3.886
75701067747273,25,100,10002455,-12,242,1,10.344.828,3.886
75701084414273,20,100,10002455,-12,242,1,10.344.828,3.886
75701101076273,23,100,10002455,-12,242,1,10.344.828,3.886
75701117739273,25,100,10002455,-12,242,1,10.344.828,3.886